import useSWR from "swr";
import Head from "next/head";
import Image from "next/image";
import { motion } from "framer-motion";

import Navbar from "../components/navbar";

const fetcher = (...args) => fetch(...args).then((res) => res.json());

const container = {
  hidden: {},
  visible: {
    transition: {
      delayChildren: 0.3,
      staggerChildren: 0.2,
    },
  },
};

const item = {
  hidden: { y: 20, opacity: 0 },
  visible: {
    y: 0,
    opacity: 1,
  },
};

export default function Food() {
  const { data, error } = useSWR("/api/businesses/search", fetcher);

  if (error) return <div>Failed to load</div>;
  if (!data) return <div>Loading...</div>;

  return (
    <>
      <Head>
        <title>Mi Casa Su Shasta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mx-24 mt-10">
        <h1 className="text-5xl text-teal-500 font-semibold">
          Mi Casa Su Shasta
        </h1>
        <p className="text-base mt-12 mb-4">
          4 Bedrooms, 2 Bathrooms, Sleeps 12, Dog & Kid Friendly, Golf Cart
          Included
        </p>
      </div>

      <div>
        <Navbar />
      </div>
      <motion.div
        className="flex flex-wrap justify-around bg-teal-500"
        variants={container}
        initial="hidden"
        animate="visible"
      >
        {data.businesses.map((business) => (
          <motion.div
            className="rounded-xl shadow-xl m-4 p-4 bg-white"
            key={business.id}
            variants={item}
          >
            <div className="mb-2">
              <h1 className="text-xl">{business.name}</h1>
              <div>{business.location.address1}</div>
              <div>{business.display_phone}</div>
              <div>{business.price}</div>
            </div>
            <div>
              <Image
                className="rounded object-cover h-40 w-80"
                src={business.image_url}
                alt="Next.js Logo"
                width={200}
                height={200}
              />
            </div>
          </motion.div>
        ))}
      </motion.div>
    </>
  );
}
