import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Mi Casa Su Shasta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-1 mb-2 mx-24 mt-10">
          <h1 className="text-5xl text-teal-500 font-semibold">
            Mi Casa Su Shasta
          </h1>
          <p className="text-base mt-12 mb-4">
            4 Bedrooms, 2 Bathrooms, Sleeps 12, Dog & Kid Friendly, Golf Cart
            Included
          </p>
        </div>

        <div>
          <div className="flex flex-col items-center bg-teal-500">
            <Image
              className="rounded"
              src="/front-wide-low.jpeg"
              alt="Next.js Logo"
              width={1920}
              height={700}
              priority
            />
            <div className="mt-16">
              <ul className="flex text-white">
                <li>
                  <div className="p-4 h-full mx-4">
                    <div className="font-semibold">House</div>
                    <ul>
                      <li>1,641 sq. ft</li>
                    </ul>
                  </div>
                </li>
                <li>
                  <div className="p-4 h-full mx-4">
                    <div className="font-semibold">4 bedrooms</div>
                    <ul className="flex">
                      <li>9 beds</li>
                      <li className="ml-2">Sleeps 12</li>
                    </ul>
                  </div>
                </li>
                <li>
                  <div className="p-4 h-full mx-4">
                    <div className="font-semibold">2 bathrooms</div>
                    <ul>
                      <li>2 full baths</li>
                    </ul>
                  </div>
                </li>
                <li>
                  <div className="p-4 h-full mx-4">
                    <div className="font-semibold">Spaces</div>
                    <ul className="flex">
                      <li>Kitchen</li>
                      <li className="ml-2">Living Room</li>
                      <li className="ml-2">Patio</li>
                    </ul>
                  </div>
                </li>
              </ul>
            </div>
            <div className="w-1/2 my-12 text-white">
              <p>
                Escape to paradise at our tropical oasis! Located right on the
                beach, this Jimmy Buffett-style Airbnb boasts breathtaking ocean
                views and a laid-back vibe. Savor the island life with a cold
                drink in hand, as you relax on the spacious deck or lounge by
                the private pool. Decorated with vibrant hues and beachy
                accents, the house exudes a fun and playful energy, just like
                the lyrics of a classic Jimmy Buffett tune. Cook up delicious
                meals in the fully-equipped kitchen or fire up the grill for a
                seaside barbecue, while you hum along to "Margaritaville" or
                "Cheeseburger in Paradise." With comfortable sleeping
                arrangements for up to X guests, this beach house is the perfect
                place for a relaxing getaway with friends or family, where life
                is just a beach away
              </p>
            </div>
          </div>
          <div className="flex flex-col items-center my-20">
            <div className="flex">
              <div className="text-teal-500 bg-yellow-100 px-36 flex flex-col justify-center">
                <h2 className="text-4xl mb-4 uppercase">Contact</h2>
                <div>Kiska Beach</div>
                <div>garysarahvarner@gmail.com</div>
                <div>
                  <a>www.airbnb.com</a>
                </div>
                <div>
                  <a>www.vrbo.com</a>
                </div>
              </div>
              <div>
                <Image
                  src="/contact-beach.jpg"
                  alt="beach scene"
                  width={600}
                  height={200}
                />
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
